#include "button_prompts.h"
#include <install/platform_paths.h>
#include <user/config.h>
#include <hid/hid.h>
#include <os/logger.h>
#include <decompressor.h>
#include <zstd.h>
#include <fstream>
#include <mutex>

// Include embedded XTD data (generated by BIN2C)
#include <res/button_prompts/xbox360.xtd.h>
#include <res/button_prompts/xbox_one.xtd.h>
#include <res/button_prompts/xbox_series_x.xtd.h>
#include <res/button_prompts/ps3.xtd.h>
#include <res/button_prompts/ps4.xtd.h>
#include <res/button_prompts/ps5.xtd.h>
#include <res/button_prompts/switch.xtd.h>
#include <res/button_prompts/steam_controller.xtd.h>
#include <res/button_prompts/steam_deck.xtd.h>

namespace ButtonPrompts
{
    static std::filesystem::path s_cacheDir;
    static std::filesystem::path s_cachedXtdPath;
    static std::string s_cachedPlatform;
    static bool s_initialized = false;
    static std::mutex s_mutex;

    // Map platform name to embedded data
    struct EmbeddedXtd
    {
        const uint8_t* data;
        size_t compressedSize;
        size_t uncompressedSize;
    };

    static EmbeddedXtd GetEmbeddedXtd(const std::string& platform)
    {
        if (platform == "xbox360")
            return { g_button_prompts_xbox360, sizeof(g_button_prompts_xbox360), g_button_prompts_xbox360_uncompressed_size };
        if (platform == "xbox_one")
            return { g_button_prompts_xbox_one, sizeof(g_button_prompts_xbox_one), g_button_prompts_xbox_one_uncompressed_size };
        if (platform == "xbox_series_x")
            return { g_button_prompts_xbox_series_x, sizeof(g_button_prompts_xbox_series_x), g_button_prompts_xbox_series_x_uncompressed_size };
        if (platform == "ps3")
            return { g_button_prompts_ps3, sizeof(g_button_prompts_ps3), g_button_prompts_ps3_uncompressed_size };
        if (platform == "ps4")
            return { g_button_prompts_ps4, sizeof(g_button_prompts_ps4), g_button_prompts_ps4_uncompressed_size };
        if (platform == "ps5")
            return { g_button_prompts_ps5, sizeof(g_button_prompts_ps5), g_button_prompts_ps5_uncompressed_size };
        if (platform == "switch")
            return { g_button_prompts_switch, sizeof(g_button_prompts_switch), g_button_prompts_switch_uncompressed_size };
        if (platform == "steam_controller")
            return { g_button_prompts_steam_controller, sizeof(g_button_prompts_steam_controller), g_button_prompts_steam_controller_uncompressed_size };
        if (platform == "steam_deck")
            return { g_button_prompts_steam_deck, sizeof(g_button_prompts_steam_deck), g_button_prompts_steam_deck_uncompressed_size };
        
        // Default fallback to xbox360
        return { g_button_prompts_xbox360, sizeof(g_button_prompts_xbox360), g_button_prompts_xbox360_uncompressed_size };
    }

    void Initialize()
    {
        std::lock_guard<std::mutex> lock(s_mutex);
        
        if (s_initialized)
            return;
        
        // Create cache directory for button prompts
        s_cacheDir = PlatformPaths::GetTempDirectory() / "button_prompts";
        
        std::error_code ec;
        std::filesystem::create_directories(s_cacheDir, ec);
        
        if (ec)
        {
            LOGF_ERROR("Failed to create button prompts cache directory: {}", ec.message());
        }
        
        s_initialized = true;
        LOG_UTILITY("[ButtonPrompts] Initialized");
    }

    std::string GetCurrentPlatformName()
    {
        // Check user override first
        if (Config::ControllerIcons != EControllerIcons::Auto)
        {
            switch (Config::ControllerIcons)
            {
                case EControllerIcons::Xbox:
                    // Use Xbox 360 as default Xbox style
                    return "xbox360";
                case EControllerIcons::PlayStation:
                    // Use PS4 as default PlayStation style
                    return "ps4";
                default:
                    break;
            }
        }
        
        // Auto mode: use detected controller
        switch (hid::g_inputDeviceExplicit)
        {
            case hid::EInputDeviceExplicit::Xbox360:
                return "xbox360";
            case hid::EInputDeviceExplicit::XboxOne:
                return "xbox_one";
            // Note: XboxSeriesX would need to be added to EInputDeviceExplicit if not present
            case hid::EInputDeviceExplicit::DualShock3:
                return "ps3";
            case hid::EInputDeviceExplicit::DualShock4:
                return "ps4";
            case hid::EInputDeviceExplicit::DualSense:
                return "ps5";
            case hid::EInputDeviceExplicit::SwitchPro:
            case hid::EInputDeviceExplicit::SwitchJCLeft:
            case hid::EInputDeviceExplicit::SwitchJCRight:
            case hid::EInputDeviceExplicit::SwitchJCPair:
                return "switch";
            // Stadia/Luna use Xbox-style prompts
            case hid::EInputDeviceExplicit::Stadia:
            case hid::EInputDeviceExplicit::Luna:
                return "xbox_one";
            default:
                // Default to Xbox 360 for unknown controllers
                return "xbox360";
        }
    }

    static bool WriteXtdToCache(const std::string& platform)
    {
        EmbeddedXtd xtd = GetEmbeddedXtd(platform);
        
        if (!xtd.data || xtd.compressedSize == 0)
        {
            LOGF_ERROR("[ButtonPrompts] No embedded data for platform: {}", platform);
            return false;
        }
        
        // Decompress the XTD data
        auto decompressedData = std::make_unique<uint8_t[]>(xtd.uncompressedSize);
        size_t result = ZSTD_decompress(decompressedData.get(), xtd.uncompressedSize, xtd.data, xtd.compressedSize);
        
        if (ZSTD_isError(result))
        {
            LOGF_ERROR("[ButtonPrompts] Failed to decompress {} XTD: {}", platform, ZSTD_getErrorName(result));
            return false;
        }
        
        // Write to cache file
        std::filesystem::path outputPath = s_cacheDir / "buttons_360.xtd";
        std::ofstream file(outputPath, std::ios::binary);
        
        if (!file)
        {
            LOGF_ERROR("[ButtonPrompts] Failed to open cache file for writing: {}", outputPath.string());
            return false;
        }
        
        file.write(reinterpret_cast<const char*>(decompressedData.get()), xtd.uncompressedSize);
        file.close();
        
        if (!file)
        {
            LOGF_ERROR("[ButtonPrompts] Failed to write XTD to cache: {}", outputPath.string());
            return false;
        }
        
        s_cachedXtdPath = outputPath;
        s_cachedPlatform = platform;
        
        printf("[ButtonPrompts] Cached %s button prompts (%zu bytes) to %s\n", 
               platform.c_str(), xtd.uncompressedSize, outputPath.string().c_str());
        fflush(stdout);
        
        return true;
    }

    std::filesystem::path GetCurrentButtonPromptsPath()
    {
        std::lock_guard<std::mutex> lock(s_mutex);
        
        if (!s_initialized)
        {
            // Late initialization
            s_cacheDir = PlatformPaths::GetTempDirectory() / "button_prompts";
            std::error_code ec;
            std::filesystem::create_directories(s_cacheDir, ec);
            s_initialized = true;
        }
        
        std::string currentPlatform = GetCurrentPlatformName();
        
        // Check if we already have the correct platform cached
        if (!s_cachedXtdPath.empty() && s_cachedPlatform == currentPlatform)
        {
            std::error_code ec;
            if (std::filesystem::exists(s_cachedXtdPath, ec))
            {
                return s_cachedXtdPath;
            }
        }
        
        // Need to write/refresh the cache
        if (WriteXtdToCache(currentPlatform))
        {
            return s_cachedXtdPath;
        }
        
        // Failed - return empty path
        return {};
    }

    void RefreshCache()
    {
        std::lock_guard<std::mutex> lock(s_mutex);
        
        // Clear cached state to force re-extraction on next request
        s_cachedXtdPath.clear();
        s_cachedPlatform.clear();
        
        LOG_UTILITY("[ButtonPrompts] Cache invalidated, will refresh on next request");
    }
}
