#include "button_prompts.h"
#include <install/platform_paths.h>
#include <user/config.h>
#include <hid/hid.h>
#include <os/logger.h>
#include <decompressor.h>
#include <zstd.h>
#include <fstream>
#include <mutex>

// Include embedded XTD data (generated by BIN2C)
#include <res/button_prompts/xbox360.xtd.h>
#include <res/button_prompts/xbox_one.xtd.h>
#include <res/button_prompts/xbox_series_x.xtd.h>
#include <res/button_prompts/ps3.xtd.h>
#include <res/button_prompts/ps4.xtd.h>
#include <res/button_prompts/ps5.xtd.h>
#include <res/button_prompts/switch.xtd.h>
#include <res/button_prompts/steam_controller.xtd.h>
#include <res/button_prompts/steam_deck.xtd.h>

namespace ButtonPrompts
{
    static std::filesystem::path s_cacheDir;
    static std::filesystem::path s_cachedXtdPath;
    static std::string s_cachedPlatform;
    static bool s_initialized = false;
    static std::mutex s_mutex;

    // Map platform name to embedded data
    struct EmbeddedXtd
    {
        const uint8_t* data;
        size_t compressedSize;
        size_t uncompressedSize;
    };

    static EmbeddedXtd GetEmbeddedXtd(const std::string& platform)
    {
        if (platform == "xbox360")
            return { g_button_prompts_xbox360, sizeof(g_button_prompts_xbox360), g_button_prompts_xbox360_uncompressed_size };
        if (platform == "xbox_one")
            return { g_button_prompts_xbox_one, sizeof(g_button_prompts_xbox_one), g_button_prompts_xbox_one_uncompressed_size };
        if (platform == "xbox_series_x")
            return { g_button_prompts_xbox_series_x, sizeof(g_button_prompts_xbox_series_x), g_button_prompts_xbox_series_x_uncompressed_size };
        if (platform == "ps3")
            return { g_button_prompts_ps3, sizeof(g_button_prompts_ps3), g_button_prompts_ps3_uncompressed_size };
        if (platform == "ps4")
            return { g_button_prompts_ps4, sizeof(g_button_prompts_ps4), g_button_prompts_ps4_uncompressed_size };
        if (platform == "ps5")
            return { g_button_prompts_ps5, sizeof(g_button_prompts_ps5), g_button_prompts_ps5_uncompressed_size };
        if (platform == "switch")
            return { g_button_prompts_switch, sizeof(g_button_prompts_switch), g_button_prompts_switch_uncompressed_size };
        if (platform == "steam_controller")
            return { g_button_prompts_steam_controller, sizeof(g_button_prompts_steam_controller), g_button_prompts_steam_controller_uncompressed_size };
        if (platform == "steam_deck")
            return { g_button_prompts_steam_deck, sizeof(g_button_prompts_steam_deck), g_button_prompts_steam_deck_uncompressed_size };
        
        // Default fallback to Xbox One for unknown platforms
        return { g_button_prompts_xbox_one, sizeof(g_button_prompts_xbox_one), g_button_prompts_xbox_one_uncompressed_size };
    }

    // Track if initialization was successful (for fallback behavior)
    static bool s_initFailed = false;

    // Forward declaration for WriteXtdToCache (defined later in this file)
    static bool WriteXtdToCache(const std::string& platform);

    void Initialize()
    {
        std::lock_guard<std::mutex> lock(s_mutex);
        
        if (s_initialized)
            return;
        
        // Write to the game textures directory so RexGlue VFS can find the file.
        // The game opens "platform:\textures\buttons_360.xtd" which resolves to
        // <gameDir>/xbox360/textures/buttons_360.xtd via the RexGlue VFS.
        s_cacheDir = PlatformPaths::GetGameDirectory() / "xbox360" / "textures";

        std::error_code ec;
        std::filesystem::create_directories(s_cacheDir, ec);

        if (ec)
        {
            LOGF_ERROR("[ButtonPrompts] Failed to create textures directory '{}': {}",
                       s_cacheDir.string(), ec.message());
            s_initFailed = true;
            // Still mark as initialized to avoid repeated attempts
        }
        else
        {
            s_initFailed = false;
            // Write eagerly so the file is present before the game first opens it
            WriteXtdToCache(GetCurrentPlatformName());
        }

        s_initialized = true;
        LOG_UTILITY("[ButtonPrompts] Initialized");
    }

    std::string GetCurrentPlatformName()
    {
        // Check user override first
        if (Config::ControllerIcons != EControllerIcons::Auto)
        {
            switch (Config::ControllerIcons)
            {
                case EControllerIcons::Xbox360:
                    return "xbox360";
                case EControllerIcons::XboxOne:
                    return "xbox_one";
                case EControllerIcons::XboxSeriesX:
                    return "xbox_series_x";
                case EControllerIcons::PlayStation3:
                    return "ps3";
                case EControllerIcons::PlayStation4:
                    return "ps4";
                case EControllerIcons::PlayStation5:
                    return "ps5";
                case EControllerIcons::NintendoSwitch:
                    return "switch";
                case EControllerIcons::SteamDeck:
                    return "steam_deck";
                case EControllerIcons::SteamController:
                    return "steam_controller";
                default:
                    break;
            }
        }
        
        // Auto mode: use detected controller
        switch (hid::g_inputDeviceExplicit)
        {
            case hid::EInputDeviceExplicit::Xbox360:
                return "xbox360";
            case hid::EInputDeviceExplicit::XboxOne:
                return "xbox_one";
            case hid::EInputDeviceExplicit::XboxSeriesX:
                return "xbox_series_x";
            case hid::EInputDeviceExplicit::DualShock3:
                return "ps3";
            case hid::EInputDeviceExplicit::DualShock4:
                return "ps4";
            case hid::EInputDeviceExplicit::DualSense:
                return "ps5";
            case hid::EInputDeviceExplicit::SwitchPro:
            case hid::EInputDeviceExplicit::SwitchJCLeft:
            case hid::EInputDeviceExplicit::SwitchJCRight:
            case hid::EInputDeviceExplicit::SwitchJCPair:
                return "switch";
            case hid::EInputDeviceExplicit::SteamDeck:
                return "steam_deck";
            case hid::EInputDeviceExplicit::SteamController:
                return "steam_controller";
            // Stadia/Luna/NvShield use Xbox-style prompts
            case hid::EInputDeviceExplicit::Stadia:
            case hid::EInputDeviceExplicit::Luna:
            case hid::EInputDeviceExplicit::NvShield:
                return "xbox_one";
            default:
                // Default to Xbox One for unknown controllers
                return "xbox_one";
        }
    }

    static bool WriteXtdToCache(const std::string& platform)
    {
        EmbeddedXtd xtd = GetEmbeddedXtd(platform);
        
        if (!xtd.data || xtd.compressedSize == 0)
        {
            LOGF_ERROR("[ButtonPrompts] No embedded data for platform: {}", platform);
            return false;
        }
        
        // Decompress the XTD data
        auto decompressedData = std::make_unique<uint8_t[]>(xtd.uncompressedSize);
        size_t result = ZSTD_decompress(decompressedData.get(), xtd.uncompressedSize, xtd.data, xtd.compressedSize);
        
        if (ZSTD_isError(result))
        {
            LOGF_ERROR("[ButtonPrompts] Failed to decompress {} XTD: {}", platform, ZSTD_getErrorName(result));
            return false;
        }
        
        // Write to cache file
        std::filesystem::path outputPath = s_cacheDir / "buttons_360.xtd";
        std::ofstream file(outputPath, std::ios::binary);
        
        if (!file)
        {
            LOGF_ERROR("[ButtonPrompts] Failed to open cache file for writing: {}", outputPath.string());
            return false;
        }
        
        file.write(reinterpret_cast<const char*>(decompressedData.get()), xtd.uncompressedSize);
        file.close();
        
        if (!file)
        {
            LOGF_ERROR("[ButtonPrompts] Failed to write XTD to cache: {}", outputPath.string());
            return false;
        }
        
        s_cachedXtdPath = outputPath;
        s_cachedPlatform = platform;
        
        printf("[ButtonPrompts] Cached %s button prompts (%zu bytes) to %s\n", 
               platform.c_str(), xtd.uncompressedSize, outputPath.string().c_str());
        fflush(stdout);
        
        return true;
    }

    std::filesystem::path GetCurrentButtonPromptsPath()
    {
        std::lock_guard<std::mutex> lock(s_mutex);
        
        if (!s_initialized)
        {
            // Late initialization — mirror the same path used in Initialize()
            s_cacheDir = PlatformPaths::GetGameDirectory() / "xbox360" / "textures";
            std::error_code ec;
            std::filesystem::create_directories(s_cacheDir, ec);
            if (ec)
            {
                LOGF_ERROR("[ButtonPrompts] Late init failed to create textures directory: {}", ec.message());
                s_initFailed = true;
            }
            s_initialized = true;
        }
        
        // If init failed, return empty path to trigger fallback to original game file
        if (s_initFailed)
        {
            return {};
        }
        
        std::string currentPlatform = GetCurrentPlatformName();
        
        // Check if we already have the correct platform cached
        if (!s_cachedXtdPath.empty() && s_cachedPlatform == currentPlatform)
        {
            std::error_code ec;
            if (std::filesystem::exists(s_cachedXtdPath, ec))
            {
                return s_cachedXtdPath;
            }
        }
        
        // Need to write/refresh the cache
        if (WriteXtdToCache(currentPlatform))
        {
            return s_cachedXtdPath;
        }
        
        // Failed - return empty path
        return {};
    }

    void RefreshCache()
    {
        std::lock_guard<std::mutex> lock(s_mutex);
        
        // Clear cached state to force re-extraction on next request
        s_cachedXtdPath.clear();
        s_cachedPlatform.clear();
        
        std::string newPlatform = GetCurrentPlatformName();
        LOGF_UTILITY("[ButtonPrompts] Cache invalidated, switching to {} prompts", newPlatform);
    }
}
